### ISSUE TITLE
Changelog on update

### ISSUE THREAD

**Issue by JohnnyJTH** [BetterLectio/BetterLectio-next#32]
To detect if the app has been updated, I propose to save the current version in local storage, and on startup check if the saved version matches the actual version. If there is an increment, fetch the changelog from GitHub releases, show them and save the new version to local storage.

**Comment by victorDigital** [comment]
https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#get-a-release-by-tag-name and get the body

**Comment by JohnnyJTH** [comment]
Added in a254f45
